# Generated by Django 5.2.11 on 2026-02-27 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('trendyol', 'Trendyol'), ('micro_export', 'Trendyol Mikro İhracat')], default='trendyol', max_length=30, verbose_name='Kanal')),
                ('store_name', models.CharField(max_length=255, verbose_name='Mağaza Adı')),
                ('seller_id', models.CharField(max_length=100, verbose_name='Satıcı / Tedarikçi ID')),
                ('api_key', models.CharField(blank=True, default='', max_length=255, verbose_name='API Key')),
                ('api_secret', models.CharField(blank=True, default='', max_length=255, verbose_name='API Secret')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Son Senkronizasyon')),
            ],
            options={
                'verbose_name': 'Pazaryeri Hesabı',
                'verbose_name_plural': 'Pazaryeri Hesapları',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Firma/Organizasyon Adı')),
            ],
            options={
                'verbose_name': 'Organizasyon',
                'verbose_name_plural': 'Organizasyonlar',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='Tarih')),
                ('from_currency', models.CharField(max_length=10, verbose_name='Kaynak Döviz')),
                ('to_currency', models.CharField(default='TRY', max_length=10, verbose_name='Hedef Döviz')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Kur')),
            ],
            options={
                'verbose_name': 'Döviz Kuru',
                'verbose_name_plural': 'Döviz Kurları',
                'unique_together': {('date', 'from_currency', 'to_currency')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marketplace_order_id', models.CharField(db_index=True, max_length=100, verbose_name='Pazaryeri Sipariş No')),
                ('order_date', models.DateTimeField(verbose_name='Sipariş Tarihi')),
                ('status', models.CharField(choices=[('Created', 'Oluşturuldu'), ('Picking', 'Hazırlanıyor'), ('Shipped', 'Kargoya Verildi'), ('Delivered', 'Teslim Edildi'), ('Cancelled', 'İptal'), ('Returned', 'İade')], max_length=30)),
                ('channel', models.CharField(choices=[('trendyol', 'Trendyol'), ('micro_export', 'Trendyol Mikro İhracat')], default='trendyol', max_length=30)),
                ('country_code', models.CharField(default='TR', max_length=5, verbose_name='Ülke Kodu')),
                ('marketplace_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.marketplaceaccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.organization')),
            ],
            options={
                'verbose_name': 'Sipariş',
                'verbose_name_plural': 'Siparişler',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marketplace_line_id', models.CharField(blank=True, default='', max_length=100, verbose_name='Pazaryeri Satır ID')),
                ('sku', models.CharField(blank=True, default='', max_length=100, verbose_name='SKU')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Adet')),
                ('status', models.CharField(blank=True, default='', max_length=30, verbose_name='Satır Durumu')),
                ('sale_price_gross', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Brüt Satış Fiyatı')),
                ('sale_price_net', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Net Satış Fiyatı (İndirim Sonrası)')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Uygulanan İndirim')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order')),
            ],
            options={
                'verbose_name': 'Sipariş Kalemi',
                'verbose_name_plural': 'Sipariş Kalemleri',
            },
        ),
        migrations.AddField(
            model_name='marketplaceaccount',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_accounts', to='core.organization'),
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('PRODUCT_COST', 'Ürün Maliyeti'), ('COMMISSION', 'Komisyon'), ('SHIPPING_FEE', 'Kargo Ücreti'), ('SERVICE_FEE', 'Hizmet Bedeli'), ('VAT_OUTPUT', 'Satış KDV'), ('VAT_INPUT', 'Alış KDV (Maliyet KDV)'), ('WITHHOLDING', 'Stopaj'), ('EARLY_PAYMENT', 'Erken Ödeme Kesintisi'), ('PENALTY', 'Ceza'), ('ADS_COST', 'Reklam Harcaması'), ('RETURN_LOSS', 'İade Zararı'), ('OTHER', 'Diğer')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tutar')),
                ('currency', models.CharField(default='TRY', max_length=10, verbose_name='Para Birimi')),
                ('occurred_at', models.DateTimeField(verbose_name='İşlem Tarihi')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='Ham API Verisi (Denetim için)')),
                ('order_item_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.orderitem')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.organization')),
            ],
            options={
                'verbose_name': 'Finansal İşlem',
                'verbose_name_plural': 'Finansal İşlemler',
            },
        ),
        migrations.CreateModel(
            name='CostRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('packaging_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Paketleme Maliyeti')),
                ('handling_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Operasyon Maliyeti')),
                ('extra_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ek Ücretler')),
                ('default_ads_cost_allocation_strategy', models.CharField(default='revenue_ratio', max_length=50, verbose_name='Varsayılan Reklam Dağıtım Stratejisi')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_rules', to='core.organization')),
            ],
            options={
                'verbose_name': 'Maliyet Kuralı',
                'verbose_name_plural': 'Maliyet Kuralları',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marketplace_sku', models.CharField(db_index=True, max_length=100, verbose_name='Pazaryeri Ürün Kodu')),
                ('barcode', models.CharField(blank=True, default='', max_length=100, verbose_name='Barkod')),
                ('title', models.CharField(max_length=500, verbose_name='Ürün Adı')),
                ('category_name', models.CharField(blank=True, default='', max_length=500, verbose_name='Kategori')),
                ('image_url', models.URLField(blank=True, default='', max_length=1000, verbose_name='Görsel URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('marketplace_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.marketplaceaccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.organization')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barcode', models.CharField(db_index=True, max_length=100, verbose_name='Barkod')),
                ('marketplace_sku', models.CharField(blank=True, default='', max_length=255, verbose_name='SKU / Varyant Kodu')),
                ('title', models.CharField(blank=True, default='', max_length=500, verbose_name='Varyant Adı')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='core.product')),
            ],
            options={
                'verbose_name': 'Ürün Varyantı',
                'verbose_name_plural': 'Ürün Varyantları',
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productvariant'),
        ),
        migrations.CreateModel(
            name='ProfitSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='Tarih')),
                ('channel', models.CharField(max_length=30)),
                ('gross_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Brüt Gelir')),
                ('net_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Net Gelir')),
                ('total_costs', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Toplam Maliyet')),
                ('profit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Net Kar')),
                ('profit_margin', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Kar Marjı (%)')),
                ('return_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='İade Oranı (%)')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_snapshots', to='core.organization')),
                ('product_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.productvariant')),
            ],
            options={
                'verbose_name': 'Kârlılık Özeti',
                'verbose_name_plural': 'Kârlılık Özetleri',
            },
        ),
        migrations.CreateModel(
            name='SyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_type', models.CharField(choices=[('orders', 'Siparişler'), ('products', 'Ürünler'), ('finance', 'Finans / Hakediş')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('running', 'Çalışıyor'), ('success', 'Başarılı'), ('failed', 'Başarısız')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Başlama')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş')),
                ('logs', models.TextField(blank=True, default='', verbose_name='Loglar')),
                ('marketplace_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to='core.marketplaceaccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to='core.organization')),
            ],
            options={
                'verbose_name': 'Senkronizasyon İşi',
                'verbose_name_plural': 'Senkronizasyon İşleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Telefon')),
                ('company', models.CharField(blank=True, default='', max_length=200, verbose_name='Şirket Adı')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kullanıcı Profili',
                'verbose_name_plural': 'Kullanıcı Profilleri',
            },
        ),
        migrations.AlterUniqueTogether(
            name='marketplaceaccount',
            unique_together={('organization', 'channel', 'seller_id')},
        ),
    ]
