# Generated by Django 5.2.11 on 2026-02-27 08:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trendyol_order_id', models.CharField(db_index=True, max_length=100, verbose_name='Trendyol Sipariş No')),
                ('order_number', models.CharField(blank=True, default='', max_length=100, verbose_name='Sipariş Numarası')),
                ('status', models.CharField(choices=[('Created', 'Oluşturuldu'), ('Picking', 'Hazırlanıyor'), ('Shipped', 'Kargoya Verildi'), ('Delivered', 'Teslim Edildi'), ('Cancelled', 'İptal'), ('Returned', 'İade'), ('Unknown', 'Bilinmiyor')], default='Unknown', max_length=30)),
                ('order_date', models.DateTimeField(blank=True, null=True, verbose_name='Sipariş Tarihi')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Toplam Tutar (TL)')),
                ('total_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Toplam İndirim (TL)')),
                ('cargo_company', models.CharField(blank=True, default='', max_length=100, verbose_name='Kargo Firması')),
                ('cargo_tracking_number', models.CharField(blank=True, default='', max_length=100, verbose_name='Kargo Takip No')),
                ('cargo_cost', models.DecimalField(decimal_places=2, default=0, help_text='Satıcıdan kesilen kargo ücreti (KDV dahil).', max_digits=10, verbose_name='Kargo Maliyeti (TL)')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Toplam Maliyet (TL)')),
                ('total_commission', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Toplam Komisyon (TL)')),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Net Kar (TL)')),
                ('profit_margin', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Kar Marjı (%)')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Ham API Verisi')),
            ],
            options={
                'verbose_name': 'Sipariş',
                'verbose_name_plural': 'Siparişler',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trendyol_id', models.CharField(db_index=True, max_length=100, verbose_name='Trendyol Ürün ID')),
                ('barcode', models.CharField(blank=True, default='', max_length=100, verbose_name='Barkod')),
                ('title', models.CharField(max_length=500, verbose_name='Ürün Adı')),
                ('product_code', models.CharField(blank=True, default='', max_length=255, verbose_name='Ürün Kodu (Model Kodu)')),
                ('brand', models.CharField(blank=True, default='', max_length=255, verbose_name='Marka')),
                ('category_name', models.CharField(blank=True, default='', max_length=500, verbose_name='Kategori')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Satış Fiyatı (TL)')),
                ('list_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Liste Fiyatı (TL)')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Alış Maliyeti (TL)')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, help_text="Trendyol'un bu ürün kategorisi için uyguladığı komisyon oranı.", max_digits=5, verbose_name='Komisyon Oranı (%)')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='KDV Oranı (%)')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Stok Adedi')),
                ('image_url', models.URLField(blank=True, default='', max_length=1000, verbose_name='Görsel URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Ham API Verisi')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trendyol_line_id', models.CharField(blank=True, default='', max_length=100, verbose_name='Trendyol Satır ID')),
                ('barcode', models.CharField(blank=True, default='', max_length=100, verbose_name='Barkod')),
                ('product_name', models.CharField(blank=True, default='', max_length=500, verbose_name='Ürün Adı')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Adet')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Satış Fiyatı (TL)')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Birim Fiyat (TL)')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='İndirim (TL)')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Alış Maliyeti (TL)')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Komisyon Oranı (%)')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Komisyon Tutarı (TL)')),
                ('cargo_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kargo Maliyeti (TL)')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='KDV Tutarı (TL)')),
                ('stopaj_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Stopaj (TL)')),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Net Kar (TL)')),
                ('profit_margin', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Kar Marjı (%)')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Ham API Verisi')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='core.product')),
            ],
            options={
                'verbose_name': 'Sipariş Kalemi',
                'verbose_name_plural': 'Sipariş Kalemleri',
            },
        ),
        migrations.CreateModel(
            name='TrendyolIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store_name', models.CharField(max_length=255, verbose_name='Mağaza Adı')),
                ('supplier_id', models.CharField(max_length=100, verbose_name='Supplier ID')),
                ('api_key', models.CharField(max_length=255, verbose_name='API Key')),
                ('api_secret', models.CharField(max_length=255, verbose_name='API Secret')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('inactive', 'Pasif'), ('error', 'Hatalı')], default='active', max_length=20)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Son Senkronizasyon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trendyol Entegrasyonu',
                'verbose_name_plural': 'Trendyol Entegrasyonları',
                'unique_together': {('user', 'supplier_id')},
            },
        ),
        migrations.CreateModel(
            name='SyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_type', models.CharField(choices=[('products', 'Ürünler'), ('orders', 'Siparişler'), ('returns', 'İadeler'), ('settlements', 'Ödemeler')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('running', 'Çalışıyor'), ('success', 'Başarılı'), ('failed', 'Başarısız')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Başlangıç')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş')),
                ('records_processed', models.PositiveIntegerField(default=0, verbose_name='İşlenen Kayıt')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Hata Mesajı')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to='core.trendyolintegration')),
            ],
            options={
                'verbose_name': 'Senkronizasyon İşi',
                'verbose_name_plural': 'Senkronizasyon İşleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trendyol_return_id', models.CharField(db_index=True, max_length=100, verbose_name='Trendyol İade ID')),
                ('barcode', models.CharField(blank=True, default='', max_length=100, verbose_name='Barkod')),
                ('product_name', models.CharField(blank=True, default='', max_length=500, verbose_name='Ürün Adı')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Adet')),
                ('reason', models.TextField(blank=True, default='', verbose_name='İade Nedeni')),
                ('status', models.CharField(choices=[('Created', 'Oluşturuldu'), ('Accepted', 'Kabul Edildi'), ('Rejected', 'Reddedildi'), ('Resolved', 'Çözümlendi')], default='Created', max_length=30)),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='İade Tarihi')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='İade Tutarı (TL)')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Ham API Verisi')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='core.order')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='core.trendyolintegration')),
            ],
            options={
                'verbose_name': 'İade',
                'verbose_name_plural': 'İadeler',
                'ordering': ['-return_date'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.trendyolintegration'),
        ),
        migrations.AddField(
            model_name='order',
            name='integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.trendyolintegration'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('packaging', 'Paketleme'), ('warehouse', 'Depo / Kira'), ('salary', 'Personel'), ('advertising', 'Reklam / Pazarlama'), ('shipping_extra', 'Ek Kargo'), ('tax', 'Vergi / Muhasebe'), ('other', 'Diğer')], default='other', max_length=30)),
                ('title', models.CharField(max_length=255, verbose_name='Açıklama')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tutar (TL)')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Tarih')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Tekrarlayan mı?')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notlar')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.trendyolintegration')),
            ],
            options={
                'verbose_name': 'Gider',
                'verbose_name_plural': 'Giderler',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barcode', models.CharField(db_index=True, max_length=100, verbose_name='Barkod')),
                ('sku', models.CharField(blank=True, default='', max_length=255, verbose_name='SKU')),
                ('size', models.CharField(blank=True, default='', max_length=50, verbose_name='Beden')),
                ('color', models.CharField(blank=True, default='', max_length=100, verbose_name='Renk')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Satış Fiyatı (TL)')),
                ('list_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Liste Fiyatı (TL)')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Stok')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='core.product')),
            ],
            options={
                'verbose_name': 'Ürün Varyantı',
                'verbose_name_plural': 'Ürün Varyantları',
                'unique_together': {('product', 'barcode')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('integration', 'trendyol_id')},
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('integration', 'trendyol_order_id')},
        ),
    ]
