# Generated by Django 5.2.11 on 2026-02-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='applied_commission_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Uygulanan Komisyon'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='applied_vat_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Uygulanan KDV'),
        ),
        migrations.AddField(
            model_name='product',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Komisyon Oranı (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Satış Fiyatı'),
        ),
        migrations.AddField(
            model_name='product',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='KDV Oranı (%)'),
        ),
    ]
