# Generated by Django 5.2.11 on 2026-03-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_orderitem_applied_commission_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='current_stock',
            field=models.IntegerField(default=0, verbose_name='Güncel Stok'),
        ),
        migrations.AddField(
            model_name='product',
            name='initial_stock',
            field=models.IntegerField(default=0, help_text='Sisteme ilk çekildiğindeki stok miktarı', verbose_name='İlk Stok'),
        ),
    ]
