# Generated by Django 5.2.11 on 2026-03-01 19:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_current_stock_product_initial_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_carrier',
            field=models.CharField(default='Trendyol Express', max_length=50, verbose_name='Varsayılan Kargo Firması'),
        ),
        migrations.AddField(
            model_name='product',
            name='desi',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6, verbose_name='Desi'),
        ),
        migrations.CreateModel(
            name='CargoPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carrier_name', models.CharField(max_length=100, verbose_name='Kargo Firması')),
                ('desi', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Desi')),
                ('price_without_vat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='KDV Hariç Fiyat (TL)')),
            ],
            options={
                'verbose_name': 'Kargo Fiyatlandırması',
                'verbose_name_plural': 'Kargo Fiyatlandırmaları',
                'unique_together': {('carrier_name', 'desi')},
            },
        ),
    ]
