# Generated by Django 5.2.11 on 2026-03-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_default_carrier_product_desi_cargopricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ürün Maliyeti (KDV Dahil)'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='cost_vat_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Maliyet KDV Oranı (%)'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='desi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Varyant Desi'),
        ),
    ]
