# Generated by Django 5.2.11 on 2026-03-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_productvariant_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Marka'),
        ),
        migrations.AddField(
            model_name='product',
            name='fast_delivery',
            field=models.BooleanField(default=False, verbose_name='Bugün Kargoda'),
        ),
        migrations.AddField(
            model_name='product',
            name='return_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='İade Oranı (%)'),
        ),
    ]
