# Generated by Django 5.1.15 on 2026-03-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product_brand_product_fast_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='trendyol_created_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Trendyol Yüklenme Tarihi'),
        ),
    ]
