# Generated by Django 5.1.15 on 2026-03-04 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_trendyol_created_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('organization', 'marketplace_order_id')},
        ),
    ]
