# Generated by Django 5.1.15 on 2026-03-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sync_redesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_status',
            field=models.CharField(choices=[('WELCOME', 'Karşılama'), ('MARKETPLACE_CONNECT', 'Pazaryeri Bağlantısı'), ('SYNCING', 'Senkronizasyon'), ('COMPLETED', 'Tamamlandı')], default='WELCOME', max_length=50, verbose_name='Onboarding Durumu'),
        ),
    ]
