# Generated by Django 5.2.12 on 2026-03-25 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_carrierflatrate'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cargoinvoice',
            new_name='core_cargoi_organiz_3b5a88_idx',
            old_name='core_cargoi_organiz_idx',
        ),
    ]
