# Generated by Django 5.2.12 on 2026-04-01 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_core_cargoi_organiz_idx_core_cargoi_organiz_3b5a88_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_date', models.DateField(verbose_name='İşlem Tarihi')),
                ('transaction_type', models.CharField(blank=True, default='', max_length=100, verbose_name='İşlem Tipi (API)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tutar')),
                ('description', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('expense_type', models.CharField(choices=[('advertising', 'Trendyol Reklam'), ('influencer', 'İnfluencer Gideri'), ('other', 'Diğer')], default='advertising', max_length=20, verbose_name='Gider Türü')),
                ('external_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Harici ID')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='Ham Veri')),
                ('marketplace_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.marketplaceaccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_expenses', to='core.organization')),
            ],
            options={
                'verbose_name': 'Reklam Gideri',
                'verbose_name_plural': 'Reklam Giderleri',
                'indexes': [models.Index(fields=['organization', 'transaction_date'], name='core_adexpe_organiz_ed8a84_idx')],
            },
        ),
    ]
