# Generated by Django 5.2.12 on 2026-04-02 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_chetransaction'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chetransaction',
            new_name='core_chetra_organiz_e89906_idx',
            old_name='core_chetx_org_type_date_idx',
        ),
        migrations.RenameIndex(
            model_name='chetransaction',
            new_name='core_chetra_order_n_1c594b_idx',
            old_name='core_chetx_order_number_idx',
        ),
        migrations.RenameIndex(
            model_name='chetransaction',
            new_name='core_chetra_barcode_13f01d_idx',
            old_name='core_chetx_barcode_idx',
        ),
        migrations.RenameIndex(
            model_name='chetransaction',
            new_name='core_chetra_organiz_57a1bb_idx',
            old_name='core_chetx_org_source_date_idx',
        ),
    ]
