# Generated by Django 5.1.15 on 2026-04-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_chetransaction_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='static_otp_code',
            field=models.CharField(blank=True, help_text='Dolu ise giriş/kayıt OTP olarak bu sabit kod kullanılır. Boşsa rastgele kod gönderilir.', max_length=10, null=True, verbose_name='Sabit OTP Kodu'),
        ),
    ]
