# Generated by Django 5.1.15 on 2026-04-02 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_add_static_otp_code_to_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desi', models.IntegerField(unique=True, verbose_name='Desi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat (KDV Dahil, TL)')),
                ('cargo_provider', models.CharField(default='Yurtiçi Kargo', max_length=100, verbose_name='Kargo Firması')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kargo Fiyatı',
                'verbose_name_plural': 'Kargo Fiyatları',
                'ordering': ['desi'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Plan Adı')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat')),
                ('interval', models.CharField(default='monthly', max_length=20, verbose_name='Periyot')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Abonelik Planı',
                'verbose_name_plural': 'Abonelik Planları',
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('cancelled', 'İptal'), ('past_due', 'Gecikmiş'), ('trialing', 'Deneme'), ('admin_override', 'Admin Kontrolü')], default='trialing', max_length=50, verbose_name='Durum')),
                ('admin_override', models.BooleanField(default=False, verbose_name='Admin Erişimi')),
                ('admin_override_reason', models.TextField(blank=True, verbose_name='Admin Notu')),
                ('trial_end', models.DateTimeField(blank=True, null=True, verbose_name='Deneme Bitiş')),
                ('current_period_end', models.DateTimeField(blank=True, null=True, verbose_name='Dönem Bitiş')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='core.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usersubscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kullanıcı Aboneliği',
                'verbose_name_plural': 'Kullanıcı Abonelikleri',
            },
        ),
    ]
