# Generated by Django 5.1.15 on 2026-04-03 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_seed_cargoprice_and_admin_override'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='order_limit',
            field=models.IntegerField(default=1000, verbose_name='Aylık Sipariş Limiti'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='plan_tier',
            field=models.CharField(default='starter', max_length=50, verbose_name='Plan Kademesi'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='store_limit',
            field=models.IntegerField(default=1, verbose_name='Mağaza Limiti'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='yearly_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Yıllık Toplam Tutar'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tutar')),
                ('currency', models.CharField(default='TRY', max_length=3, verbose_name='Para Birimi')),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('success', 'Başarılı'), ('failed', 'Başarısız'), ('refunded', 'İade Edildi')], default='pending', max_length=20, verbose_name='Durum')),
                ('merchant_oid', models.CharField(max_length=200, unique=True, verbose_name='Sipariş No (PayTR)')),
                ('paytr_token', models.CharField(blank=True, max_length=500, null=True, verbose_name='PayTR Token')),
                ('paytr_response', models.JSONField(blank=True, null=True, verbose_name='PayTR Yanıtı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.subscriptionplan')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.usersubscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ödeme',
                'verbose_name_plural': 'Ödemeler',
                'ordering': ['-created_at'],
            },
        ),
    ]
