# Generated by Django 4.2.30 on 2026-05-24 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_expand_order_status_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Firma Adı')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Kod')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Kargo Firması',
                'verbose_name_plural': 'Kargo Firmaları',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CargoRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('desi_kg', models.IntegerField(verbose_name='Desi/KG')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat (KDV Dahil, TL)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Kargo Fiyatı (Satıcı Bazlı)',
                'verbose_name_plural': 'Kargo Fiyatları (Satıcı Bazlı)',
                'ordering': ['desi_kg', 'cargo_company__name'],
            },
        ),
        migrations.CreateModel(
            name='CargoRateImportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=255, verbose_name='Dosya Adı')),
                ('imported_rows', models.IntegerField(default=0, verbose_name='Başarılı Satır')),
                ('failed_rows', models.IntegerField(default=0, verbose_name='Hatalı Satır')),
                ('status', models.CharField(choices=[('success', 'Başarılı'), ('partial', 'Kısmi'), ('failed', 'Başarısız')], default='success', max_length=20, verbose_name='Durum')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Hata Mesajı')),
            ],
            options={
                'verbose_name': 'Kargo Fiyat İçe Aktarma Geçmişi',
                'verbose_name_plural': 'Kargo Fiyat İçe Aktarma Geçmişleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerCargoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('use_order_cargo_company', models.BooleanField(default=True, help_text='Trendyol siparişinden kargo firması gelirse onu kullan.', verbose_name='Siparişteki kargo firmasını kullan')),
                ('use_default_if_missing', models.BooleanField(default=True, help_text='Sipariş verisinde kargo firması yoksa varsayılan firmayı kullan.', verbose_name='Firma gelmezse varsayılanı kullan')),
                ('apply_barem_0_199', models.BooleanField(default=True, help_text='Kâr hesabında 0-199₺ arası kargo barem desteğini uygula.', verbose_name='0₺ - 199₺ barem indirimi uygula')),
                ('apply_barem_200_349', models.BooleanField(default=True, help_text='Kâr hesabında 200-349₺ arası kargo barem desteğini uygula.', verbose_name='200₺ - 349₺ barem indirimi uygula')),
                ('custom_note', models.TextField(blank=True, default='', verbose_name='Not')),
            ],
            options={
                'verbose_name': 'Satıcı Kargo Ayarı',
                'verbose_name_plural': 'Satıcı Kargo Ayarları',
            },
        ),
        migrations.RenameIndex(
            model_name='chetransaction',
            new_name='core_chetra_account_b9cde9_idx',
            old_name='core_chetra_account_3f3e5a_idx',
        ),
        migrations.RenameIndex(
            model_name='chetransaction',
            new_name='core_chetra_payment_c17409_idx',
            old_name='core_chetra_payment_64cc5c_idx',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Created', 'Oluşturuldu'), ('Picking', 'Hazırlanıyor'), ('Invoiced', 'Faturalandı'), ('Shipped', 'Kargoya Verildi'), ('AtCollectionPoint', 'Teslimat Noktasında'), ('Delivered', 'Teslim Edildi'), ('Cancelled', 'İptal'), ('Returned', 'İade'), ('UnDelivered', 'Teslim Edilemedi'), ('UnSupplied', 'Tedarik Edilemedi'), ('UnPacked', 'Paket Bölündü'), ('Repack', 'Tekrar Paketlendi'), ('Awaiting', 'Ödeme Bekliyor')], max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Bekliyor'), ('paid', 'Ödendi'), ('success', 'Başarılı (PayTR)'), ('failed', 'Başarısız'), ('refunded', 'İade Edildi'), ('overdue', 'Gecikmiş')], default='pending', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Aktif'), ('passive', 'Pasif'), ('trial', 'Deneme'), ('trialing', 'Deneme (eski)'), ('cancelled', 'İptal'), ('expired', 'Süresi Doldu'), ('suspended', 'Askıya Alındı'), ('past_due', 'Gecikmiş'), ('admin_override', 'Admin Kontrolü')], default='trialing', max_length=50, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='trial_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deneme Bitiş (eski)'),
        ),
        migrations.AddField(
            model_name='sellercargosettings',
            name='default_cargo_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cargocompany', verbose_name='Varsayılan Kargo Firması'),
        ),
        migrations.AddField(
            model_name='sellercargosettings',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_settings', to='core.organization'),
        ),
        migrations.AddField(
            model_name='cargorateimporthistory',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_rate_imports', to='core.organization'),
        ),
        migrations.AddField(
            model_name='cargorate',
            name='cargo_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='core.cargocompany'),
        ),
        migrations.AddField(
            model_name='cargorate',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Boşsa global varsayılan fiyattır.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargo_rates', to='core.organization'),
        ),
        migrations.AddIndex(
            model_name='cargorate',
            index=models.Index(fields=['organization', 'cargo_company'], name='core_cargor_organiz_53ee3d_idx'),
        ),
        migrations.AddConstraint(
            model_name='cargorate',
            constraint=models.UniqueConstraint(fields=('organization', 'cargo_company', 'desi_kg'), name='unique_org_company_desi'),
        ),
    ]
