# Generated by Django 4.2.30 on 2026-05-24 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_cargocompany_cargorate_cargorateimporthistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoRateUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='Dosya Adı')),
                ('row_count', models.IntegerField(default=0, verbose_name='Toplam Satır')),
                ('valid_row_count', models.IntegerField(default=0, verbose_name='Başarılı Satır')),
                ('failed_row_count', models.IntegerField(default=0, verbose_name='Hatalı Satır')),
                ('status', models.CharField(choices=[('success', 'Başarılı'), ('partial', 'Kısmi'), ('failed', 'Başarısız')], default='success', max_length=20, verbose_name='Durum')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Hata Mesajı')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yüklenme Tarihi')),
            ],
            options={
                'verbose_name': 'Kargo Yükleme Geçmişi',
                'verbose_name_plural': 'Kargo Yükleme Geçmişleri',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DefaultCargoRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('desi', models.IntegerField(verbose_name='Desi')),
                ('price_vat_included', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat (KDV Dahil)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Sistem Varsayılan Kargo Fiyatı',
                'verbose_name_plural': 'Sistem Varsayılan Kargo Fiyatları',
                'ordering': ['cargo_company__name', 'desi'],
            },
        ),
        migrations.CreateModel(
            name='SellerCustomCargoRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('desi', models.IntegerField(verbose_name='Desi')),
                ('price_vat_included', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat (KDV Dahil)')),
                ('currency', models.CharField(default='TRY', max_length=10, verbose_name='Para Birimi')),
                ('source', models.CharField(default='uploaded_excel', max_length=50, verbose_name='Kaynak')),
                ('upload_batch_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Yükleme ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Satıcı Özel Kargo Fiyatı',
                'verbose_name_plural': 'Satıcı Özel Kargo Fiyatları',
                'ordering': ['organization', 'desi'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='cargorate',
            name='unique_org_company_desi',
        ),
        migrations.RemoveField(
            model_name='cargorate',
            name='cargo_company',
        ),
        migrations.RemoveField(
            model_name='cargorate',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='cargorateimporthistory',
            name='organization',
        ),
        migrations.RenameIndex(
            model_name='chetransaction',
            new_name='core_chetra_account_b9cde9_idx',
            old_name='core_chetra_account_3f3e5a_idx',
        ),
        migrations.RenameIndex(
            model_name='chetransaction',
            new_name='core_chetra_payment_c17409_idx',
            old_name='core_chetra_payment_64cc5c_idx',
        ),
        migrations.RemoveField(
            model_name='sellercargosettings',
            name='apply_barem_0_199',
        ),
        migrations.RemoveField(
            model_name='sellercargosettings',
            name='apply_barem_200_349',
        ),
        migrations.RemoveField(
            model_name='sellercargosettings',
            name='custom_note',
        ),
        migrations.RemoveField(
            model_name='sellercargosettings',
            name='use_default_if_missing',
        ),
        migrations.RemoveField(
            model_name='sellercargosettings',
            name='use_order_cargo_company',
        ),
        migrations.AddField(
            model_name='sellercargosettings',
            name='apply_barem_discount_0_199',
            field=models.BooleanField(default=True, verbose_name='0₺ - 199₺ barem indirimi uygula'),
        ),
        migrations.AddField(
            model_name='sellercargosettings',
            name='apply_barem_discount_200_349',
            field=models.BooleanField(default=True, verbose_name='200₺ - 349₺ barem indirimi uygula'),
        ),
        migrations.AddField(
            model_name='sellercargosettings',
            name='use_custom_cargo_rates',
            field=models.BooleanField(default=False, verbose_name='Özel kargo fiyatlarını kullan'),
        ),
        migrations.AddField(
            model_name='sellercargosettings',
            name='use_trendyol_real_cargo_if_available',
            field=models.BooleanField(default=True, verbose_name='Trendyol gerçek faturası varsa kullan'),
        ),
        migrations.DeleteModel(
            name='CargoRate',
        ),
        migrations.DeleteModel(
            name='CargoRateImportHistory',
        ),
        migrations.AddField(
            model_name='sellercustomcargorate',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_cargo_rates', to='core.organization'),
        ),
        migrations.AddField(
            model_name='defaultcargorate',
            name='cargo_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_rates', to='core.cargocompany'),
        ),
        migrations.AddField(
            model_name='cargorateupload',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_uploads', to='core.organization'),
        ),
        migrations.AddIndex(
            model_name='sellercustomcargorate',
            index=models.Index(fields=['organization', 'desi', 'is_active'], name='core_seller_organiz_9c55da_idx'),
        ),
        migrations.AddConstraint(
            model_name='defaultcargorate',
            constraint=models.UniqueConstraint(fields=('cargo_company', 'desi'), name='unique_default_company_desi'),
        ),
    ]
